name: 'Setup OpenModelica environment'
description: 'Set up a OpenModelica environment and add it to the PATH'
author: 'Andreas Heuermann'
inputs:
  version:
    description: 'The OpenModelica release version to use. Example: 1.19.0'
    required: false
    default: '1.19.0'
runs:
  using: 'node16'
  main: 'dist/index.js'
